data_load:
  raw_dataset: "data/raw/test_scores.csv"

data_split:
  test_size: 0.2
  random_state: 42
  trainset_path: "data/processed/train.csv"
  testset_path: "data/processed/test.csv"


models:
  linear_regression:
    fit_intercept: true

  decision_tree:
    max_depth: 4
    random_state: 42

  xgboost:
    n_estimators: 100
    max_depth: 4
    learning_rate: 0.1

  catboost:
    iterations: 200
    depth: 4
    learning_rate: 0.1

  neural_network:
    hidden_layer_sizes: [100, 50]
    activation: relu
    solver: adam
    max_iter: 500
    random_state: 42
